#!/usr/bin/env python3
"""murderboard_agents.py — compile `doc_review_process.md` into one agent file per role.

THE GAP THIS CLOSES. The review team is eleven specialists, and until now they existed only
as eleven numbered blocks of prose inside a single ~95KB document. That works when a human
reads it. It fails three ways when agents run it:

  1. Nothing granted a role the ability to do its own check. "DOI or Die" spawned without web
     access still returns a paragraph about citations, and that paragraph is indistinguishable
     in the report from one written after resolving them. The process file's own rule — *can
     the alarm ring?* — applies to the reviewers, and nothing was applying it.
  2. Every role was handed the whole document, including ten checklists that are not its own.
  3. The team was invisible. Nothing listed the specialists anywhere a person or a harness
     could see them; you had to already know they were in there.

THE THING THIS MUST NOT DO is create a second copy of any rule. This repo has already paid
for that failure once (two copies of the published page, drifted). So the agent files are
COMPILED, never authored: every word in them is sliced out of `doc_review_process.md`, which
stays the single authority. `tests/agents_generated_test.py` regenerates and diffs, so a
hand-edit to an agent file fails CI instead of quietly becoming a fork.

USAGE
  murderboard_agents.py write            regenerate agents/ from the process file
  murderboard_agents.py check            regenerate in memory; exit 1 if agents/ disagrees

OUTPUT GOES IN A DIRECTORY THIS TOOL OWNS. `.claude/agents/` is the harness's SHARED project
agent directory; the eleven land in `.claude/agents/murderboard/` beneath it, which nothing else
writes to. The harness scans recursively and identity comes from the `name` frontmatter rather
than the path, so nesting costs nothing. Removing "anything here that is not mine" is then true
by construction rather than by a check that has to stay correct. See `default_dir()` for why,
and `ours()` for the incident that made it necessary and for the backstop that remains.
  murderboard_agents.py list             print "N<TAB>agent-name<TAB>path" per role
  murderboard_agents.py verify REPORT.md did the run record account for the grants its
                                         reviewers actually held?
  murderboard_agents.py --process PATH   use this process file (default: autodetect)
  murderboard_agents.py --dir PATH       write/read agent files here
                                         (default: <root>/.claude/agents/murderboard)
  murderboard_agents.py --selftest       prove every branch can still fire

`verify` is the other half of the grant. Compiling a tool list into an agent file says what a
role SHOULD hold; it cannot say what the role WAS handed, and a fallback spawn -- an unregistered
agent, a harness that never loaded the plugin -- quietly substitutes a different tool set. So
every role opens its output with `GRANT <n> ok` or `GRANT <n> MISMATCH`, and `verify` refuses a
report claiming `named agents` while its own reviewers said otherwise. A MISMATCH is not a failed
run: a fallback review is a real review, it just may not be written up as something else.

EXIT CODES   0 = ok   1 = agents/ is out of date (check) / the report does not account for its
             grants (verify)   2 = could not determine

Stdlib only, project-neutral: no hardcoded consumer paths, no third-party imports. A consumer
vendors THIS FILE, not the eleven it produces — so when upstream adds role 12, re-vendoring
the process file and re-running `write` picks it up with no config to edit. A vendored list of
eleven filenames would have silently stayed eleven.
"""

import argparse
import json
import pathlib
import re
import subprocess
import sys
import tempfile
import textwrap

TEAM_HEADING = "## The review team"
GRANTS_HEADING = "### What each role must be able to reach"
OPTIONAL_HEADING = "### The team is not optional"

# Paragraphs sliced verbatim into every agent file, identified by their opening words. A
# missing block is a HARD ERROR, never a silently shorter agent file: if someone rewords the
# process file's opening, this must stop and say so, because "regenerate and the diff went
# away" would otherwise launder a dropped rule into a passing test.
SHARED_BLOCKS = (
    ("output contract", "**Each role returns a structured finding list**"),
    ("no-edit rule", "**No reviewer may edit the artifact.**"),
    ("grant declaration", "**Every reviewer declares its grant before it reviews.**"),
    ("silence is not a result", "A role with genuinely nothing to check returns"),
)

PROCESS_CANDIDATES = (
    "docs/doc_review_process.md",
    "doc_review_process.md",
    ".claude/skills/murderboard/doc_review_process.md",
)

BANNER = (
    "<!-- GENERATED by murderboard_agents.py from doc_review_process.md — DO NOT EDIT.\n"
    "     Edit the role in the process file and re-run `murderboard_agents.py write`.\n"
    "     A hand-edit here is a second copy of a rule; CI regenerates and diffs. -->"
)


class ProcessError(Exception):
    """The process file does not have the shape this compiler requires."""


# --- locating -----------------------------------------------------------------


def repo_root():
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        )
        return pathlib.Path(out.stdout.strip())
    except (subprocess.CalledProcessError, FileNotFoundError):
        return pathlib.Path.cwd()


def resolve_process(explicit):
    if explicit:
        p = pathlib.Path(explicit)
        if not p.is_file():
            raise ProcessError("cannot read process file %s" % p)
        return p
    root = repo_root()
    for rel in PROCESS_CANDIDATES:
        p = root / rel
        if p.is_file():
            return p
    raise ProcessError("no doc_review_process.md found under %s (use --process PATH)" % root)


# --- parsing ------------------------------------------------------------------


def team_section(text):
    """The lines between '## The review team' and the next '## ' heading."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith(TEAM_HEADING):
            start = i + 1
            break
    if start is None:
        raise ProcessError("process file has no '%s' section" % TEAM_HEADING)
    for j in range(start, len(lines)):
        if lines[j].startswith("## "):
            return lines[start:j]
    return lines[start:]


ROLE_RE = re.compile(r"^(\d+)\. \*\*(.+?)\*\*")


def parse_roles(team):
    """One entry per numbered role, body verbatim and dedented.

    Scoped exactly like murderboard_roster.sh: column 0 only, inside the team section only.
    A role's body runs to the next role or the next '### ' subheading — the grants table and
    'the team is not optional' are subheadings, so they terminate role 11 rather than being
    swallowed into it.
    """
    starts = [i for i, line in enumerate(team) if ROLE_RE.match(line)]
    if not starts:
        raise ProcessError("parsed 0 roles from the team section — refusing to emit nothing")

    stops = []
    for k, i in enumerate(starts):
        limit = starts[k + 1] if k + 1 < len(starts) else len(team)
        end = limit
        for j in range(i + 1, limit):
            if team[j].startswith("### "):
                end = j
                break
        stops.append(end)

    roles = []
    for i, end in zip(starts, stops):
        m = ROLE_RE.match(team[i])
        num, title = m.group(1), m.group(2)
        indent = len(num) + 2  # "1. " -> 3, "10. " -> 4
        body = [team[i][len(num) + 2:]]
        for line in team[i + 1:end]:
            body.append(line[indent:] if line[:indent].strip() == "" else line)
        while body and not body[-1].strip():
            body.pop()
        roles.append({"num": int(num), "title": title, "body": body})
    return roles


GRANT_ROW_RE = re.compile(r"^\|\s*(\d+)\s*\|([^|]*)\|([^|]*)\|([^|]*)\|\s*$")


def parse_grants(team):
    """The '# | role | may reach | model' table, keyed by role number."""
    try:
        at = next(i for i, line in enumerate(team) if line.startswith(GRANTS_HEADING))
    except StopIteration:
        raise ProcessError("process file has no '%s' subsection" % GRANTS_HEADING)
    grants = {}
    for line in team[at:]:
        if line.startswith("### ") and not line.startswith(GRANTS_HEADING):
            break
        m = GRANT_ROW_RE.match(line)
        if not m:
            continue
        num, nick, tools, model = (g.strip() for g in m.groups())
        grants[int(num)] = {
            "nickname": nick,
            "tools": ", ".join(t.strip() for t in tools.split(",") if t.strip()),
            "model": model,
        }
    if not grants:
        raise ProcessError("the '%s' table parsed 0 rows" % GRANTS_HEADING)
    return grants


def parse_shared(text, team):
    """The paragraphs every agent file carries, sliced out of the process file."""
    optional = text.split(OPTIONAL_HEADING, 1)
    in_team = "\n".join(team)
    haystacks = {
        "output contract": in_team,
        "no-edit rule": in_team,
        "grant declaration": in_team,
        "silence is not a result": optional[1] if len(optional) > 1 else "",
    }
    blocks = {}
    for label, opener in SHARED_BLOCKS:
        blocks[label] = paragraph_starting(haystacks[label], opener, label)
    return blocks


def paragraph_starting(haystack, opener, label):
    at = haystack.find(opener)
    if at < 0:
        raise ProcessError(
            "could not find the %s block (expected a paragraph opening %r). "
            "If it was reworded, update SHARED_BLOCKS — do not let it silently drop out of "
            "every agent file." % (label, opener)
        )
    rest = haystack[at:]
    end = rest.find("\n\n")
    return (rest if end < 0 else rest[:end]).strip()


# --- rendering ----------------------------------------------------------------


def slug_of(nickname):
    s = nickname.lower().replace("'", "").replace("’", "")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    if not s:
        raise ProcessError("role nickname %r produced an empty slug" % nickname)
    return s


MARKUP_RE = re.compile(r"(\*\*|\*|`|_)")


def first_sentence(body_lines, limit=320):
    """A one-line description for the frontmatter, derived from the role's own opening.

    Derived, not authored: a description that can be edited independently of the checklist it
    describes is one more thing that can drift away from it.
    """
    text = " ".join(line.strip() for line in body_lines)
    text = text.split("**", 2)[-1] if text.startswith("**") else text
    text = MARKUP_RE.sub("", text).strip()
    text = re.sub(r"\s+", " ", text)
    m = re.search(r"(?<=[.!?])\s+(?=[A-Z(])", text)
    sentence = text[:m.start()] if m else text
    if len(sentence) > limit:
        sentence = sentence[:limit].rsplit(" ", 1)[0] + "…"
    return sentence.strip()


def render_agent(role, grant, shared, preamble, total):
    num, title = role["num"], role["title"]
    plain_title = MARKUP_RE.sub("", title).strip()
    desc = "Murderboard role %d of %d, %s %s" % (num, total, plain_title, first_sentence(role["body"]))
    # QUOTED, and every embedded double quote already downgraded to a single one. Role
    # descriptions are sliced from prose that routinely contains ": " ("Clarity and precision:
    # undefined jargon"), and a bare YAML scalar containing ": " is a parse error — the agent
    # would not load at all, which is the one failure mode this file exists to prevent.
    desc = desc.replace('"', "'").replace("\\", "/").replace("\n", " ")

    out = []
    out.append("---")
    out.append("name: murderboard-%s" % slug_of(grant["nickname"]))
    out.append('description: "%s"' % desc)
    out.append("tools: %s" % grant["tools"])
    out.append("model: %s" % grant["model"])
    out.append("---")
    out.append("")
    out.append(BANNER)
    out.append("")
    out.append("# %s" % re.sub(r'\.("?)$', r"\1", plain_title))
    out.append("")
    out.extend(textwrap.wrap(
        "You are role %d of %d on the murderboard review team. The other %d run in parallel with "
        "you and you will not see their findings: do not widen your scope to cover them, and do "
        "not narrow it because you assume they have it. Your boundaries with the other roles are "
        "stated inside your checklist below, and `doc_review_process.md` is the authority if you "
        "need more than that." % (num, total, total - 1), width=98))
    out.append("")
    out.append("## How the team operates")
    out.append("")
    out.append(shared["output contract"])
    out.append("")
    out.append(shared["silence is not a result"])
    out.append("")
    out.append(shared["no-edit rule"])
    out.append("")
    out.extend(preamble)
    out.append("")
    out.append("## Before you review — declare your grant")
    out.append("")
    out.append(shared["grant declaration"])
    out.append("")
    # The two forms go in a literal block, NOT into the wrapped prose above them. A reviewer
    # copying a line that textwrap split across two lines produces something `verify` cannot
    # match, and the gate then reports a role that never declared a grant it did declare.
    out.extend(textwrap.wrap(
        "**The process file grants you `%s`, and nothing else.** Compare that against the tools "
        "you were actually given, then open your output with exactly one of these two lines:"
        % grant["tools"], width=98))
    out.append("")
    out.append("    GRANT %d ok — %s" % (num, grant["tools"]))
    out.append("    GRANT %d MISMATCH — missing <tools>; holds <forbidden tools>" % num)
    out.append("")
    out.extend(textwrap.wrap(
        "Use the second whenever they differ — you are missing one of your tools, or you hold an "
        "editing tool no reviewer may have. Do not adjust your review to hide the gap and do not "
        "skip the line: a reviewer that cannot do its check is a finding, and an undeclared one "
        "is the exact failure this team exists to catch.", width=98))
    out.append("")
    out.append("## Your checklist")
    out.append("")
    out.extend(role["body"])
    out.append("")
    return "\n".join(out)


PREAMBLE_START = "**Roles are split by what it COSTS to satisfy them"


def preamble_notes(team):
    """The boundary paragraphs at the top of the team section.

    Every role needs to know how the split works — 'file it once', mechanical vs judgment,
    unit of analysis — because that is what stops two roles reporting the same defect and one
    role reporting nobody's.

    The preamble is split by POSITION: everything before the 'Roles are split by what it COSTS'
    paragraph is addressed to the harness (spawn them like this, the contract is two paragraphs
    for this reason) and is dropped; that paragraph onward is addressed to the reviewers and is
    carried. So a new harness note goes above the line and a new boundary rule goes below it.
    Getting that backwards leaks compiler trivia into eleven agent files, or drops a rule from
    them — hence the hard failure if the anchor is gone.
    """
    block = []
    for line in team:
        if ROLE_RE.match(line):
            break
        block.append(line)
    text = "\n".join(block)
    at = text.find(PREAMBLE_START)
    if at < 0:
        raise ProcessError(
            "the team preamble has no paragraph opening %r, so there is no line between what is "
            "addressed to the harness and what is addressed to the reviewers. Restore it or "
            "update PREAMBLE_START — do not let the split be guessed." % PREAMBLE_START
        )
    notes = []
    for para in text[at:].strip().split("\n\n"):
        para = para.strip()
        if para:
            notes.append(para)
            notes.append("")
    if notes:
        notes.pop()
    return notes


def compile_agents(process_path):
    return compile_all(process_path)["files"]


def compile_all(process_path):
    """{"files": {name: body}, "grants": {n: {...}}} — everything parsed out of the process file.

    `verify` needs the grants without the rendered files; everything else needs the files. Both
    come from one parse so the two can never be answering from different readings of the same
    document.
    """
    text = process_path.read_text(encoding="utf-8")
    team = team_section(text)
    roles = parse_roles(team)
    grants = parse_grants(team)
    shared = parse_shared(text, team)
    preamble = preamble_notes(team)

    missing = [r["num"] for r in roles if r["num"] not in grants]
    if missing:
        raise ProcessError(
            "roles %s have no row in the '%s' table. A role with no grant would be spawned "
            "able to reach everything or nothing, and neither is a decision anyone made."
            % (missing, GRANTS_HEADING)
        )
    extra = sorted(set(grants) - {r["num"] for r in roles})
    if extra:
        raise ProcessError(
            "the '%s' table has rows %s with no matching role. A grant for a role that does "
            "not exist means the table and the checklists have already drifted."
            % (GRANTS_HEADING, extra)
        )

    total = len(roles)
    out = {}
    for role in roles:
        grant = grants[role["num"]]
        name = "%02d-%s.md" % (role["num"], slug_of(grant["nickname"]))
        out[name] = render_agent(role, grant, shared, preamble, total)
    return {"files": out, "grants": grants}


# --- commands -----------------------------------------------------------------


BANNER_MARK = "GENERATED by murderboard_agents.py"
NAMESPACE = "murderboard"


def default_dir(root):
    """Where agent files go when `--dir` is not given.

    NAMESPACED, AND THAT IS THE WHOLE FIX. `.claude/agents/` is the harness's SHARED project
    agent directory -- the consumer's own subagents live there. Writing the eleven into it and
    then tidying up is how this tool deleted a consumer's agents (see `ours()`). Writing them
    into `.claude/agents/murderboard/` instead means the tool owns its directory outright and
    "remove anything here that is not mine" is true by construction. The capability to destroy
    somebody else's file is not guarded; it does not exist.

    Safe because the harness scans `.claude/agents/` RECURSIVELY and a subagent's identity comes
    from its `name` frontmatter, never from its path -- so a subfolder changes nothing about how
    these load. (Confirmed against the sub-agents reference, 2026-08-28. Note the corollary: the
    namespace does NOT isolate NAMES. Two files anywhere under the same `.claude/agents/` tree
    declaring one name resolve by filesystem read order, which is why every generated name is
    prefixed and why the uniqueness assertion in the test suite matters.)

    THE MURDERBOARD'S OWN CHECKOUT IS THE EXCEPTION: it is the plugin, and a plugin ships its
    agents at `agents/` in its root. Detected by NAME out of the plugin manifest, not by "does a
    `.claude-plugin/` directory exist" -- a consumer may publish plugins of their own, and that
    heuristic would send their reviewers to a top-level `agents/` the harness never reads, where
    the run would quietly take the fallback path and still report success.
    """
    manifest = root / ".claude-plugin" / "plugin.json"
    try:
        if json.loads(manifest.read_text(encoding="utf-8")).get("name") == NAMESPACE:
            if (root / "agents").is_dir():
                return root / "agents"
    except (OSError, ValueError):
        pass
    return root / ".claude" / "agents" / NAMESPACE


def ours(path):
    """Did THIS tool write this file? Only the banner answers that.

    THE INCIDENT. `write` deleted every `*.md` in `--dir` that was not one of the eleven, and
    every consumer-facing instruction pointed `--dir` at the SHARED `.claude/agents`. A consumer
    with their own subagents lost them, silently, on their first `/murderboard` run, because
    SKILL step 4a runs `check || write` unattended. Reproduced: two files in, zero files out.

    THIS IS THE BACKSTOP, NOT THE FIX. `default_dir()` is the fix: own the directory and there
    is nothing of anyone else's in it to delete. This function survives for the case where a
    consumer overrides `--dir` back onto a shared path, and because a guard that costs one file
    read is worth keeping under a structural fix rather than instead of one.

    Ownership is a property of the file's CONTENT, never of its name or its directory. A file
    matching `NN-slug.md` without the banner is somebody else's and is never touched; an
    unreadable file is never touched either, because "I could not read it" is not evidence that
    it is mine to delete.
    """
    try:
        return BANNER_MARK in path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False


def ensure_dir(target):
    """A `--dir` that exists and is not a directory is exit 2, not a traceback."""
    if target.exists() and not target.is_dir():
        print("murderboard_agents: --dir %s exists and is not a directory" % target,
              file=sys.stderr)
        return False
    return True


def cmd_write(agents, target):
    if not ensure_dir(target):
        return 2
    target.mkdir(parents=True, exist_ok=True)
    written, removed, foreign = [], [], []
    for name, body in sorted(agents.items()):
        path = target / name
        try:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
        except (OSError, UnicodeDecodeError):
            current = None
        if current != body:
            path.write_text(body, encoding="utf-8")
            written.append(name)
    # A renamed role leaves its old file behind, and a stale agent file is a role that runs
    # under a name the roster no longer knows — worse than a missing one. But only OUR stale
    # files: see `ours()` for what this used to do to everyone else's.
    for path in sorted(target.glob("*.md")):
        if path.name in agents:
            continue
        if ours(path):
            path.unlink()
            removed.append(path.name)
        else:
            foreign.append(path.name)
    print("murderboard_agents: %d agents in %s (%d written, %d removed, %d left alone)"
          % (len(agents), target, len(written), len(removed), len(foreign)))
    for name in written:
        print("  wrote      %s" % name)
    for name in removed:
        print("  removed    %s" % name)
    for name in foreign:
        print("  not ours   %s" % name)
    return 0


def cmd_check(agents, target):
    problems = []
    if not ensure_dir(target):
        return 2
    if not target.is_dir():
        problems.append("%s does not exist — run `murderboard_agents.py write`" % target)
    else:
        for name, body in sorted(agents.items()):
            path = target / name
            if not path.is_file():
                problems.append("missing  %s" % name)
                continue
            try:
                current = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError) as e:
                problems.append("unreadable %s (%s)" % (name, e.__class__.__name__))
                continue
            if current != body:
                problems.append("stale    %s (differs from the process file)" % name)
        # Only OUR orphans. A consumer's own agent sitting in the same directory is not a
        # defect in this repo's output, and reporting it as one is what made `check || write`
        # fire the delete that ate it.
        for path in sorted(target.glob("*.md")):
            if path.name not in agents and ours(path):
                problems.append("orphan   %s (no such role in the process file)" % path.name)
    if problems:
        for p in problems:
            print("  %s" % p, file=sys.stderr)
        print("murderboard_agents: %s is out of date with doc_review_process.md — "
              "run `murderboard_agents.py write`" % target, file=sys.stderr)
        return 1
    print("murderboard_agents: all %d agent files agree with the process file" % len(agents))
    return 0


# Deliberately generous about FORMAT and strict about PRESENCE, the same stance
# murderboard_roster.sh takes: the line may sit in a table cell, a bullet or a paragraph. What
# it may not do is be absent.
#
# The trailing group is the tool list after the dash, and capturing it is the whole of the fix
# for a gate that used to read the verdict token and nothing else. `[^\n|]*` stops at a table
# cell wall, so `| 1 | Prove It | GRANT 1 ok — Read, Bash |` yields `Read, Bash `, not the rest
# of the row. All three dashes people actually type are accepted. The list is OPTIONAL in the
# pattern on purpose: a declaration missing it must be a reported problem, and a pattern that
# required it would simply fail to match and report "never declared", which blames the wrong
# thing and tells the author to add a line that is already there.
GRANT_LINE_RE = re.compile(
    r"GRANT\s+(\d+)\s+(ok|MISMATCH)\b[ \t]*(?:[—–-]+[ \t]*([^\n|]*))?", re.I)
ROLES_LINE_RE = re.compile(r"roles:\s*(\d+)\s+of\s+(\d+)\s+run\s*\(([^)]*)\)", re.I)
NAMED_MODES = ("named agent",)

# `GRANT n MISMATCH — missing <tools>; holds <forbidden tools>` is the INSTRUCTION every compiled
# agent file carries, not a verdict any reviewer reached. A run record that documents how its
# reviewers were spawned quotes that file, so without this the quotation reads as eleven
# mismatches and the gate fails the most thorough reports it will ever see. An angle-bracket
# placeholder is not a tool name: a declaration built out of them declares nothing and is
# skipped, which leaves the role UNDECLARED and failing, never passing.
PLACEHOLDER_RE = re.compile(r"<[^>]*>")


def tool_set(raw):
    """A comma-separated tool list, normalised for set comparison."""
    return frozenset(t.strip().lower() for t in raw.split(",") if t.strip())


def cmd_verify(report_path, grants):
    """Does the report's claim about HOW its reviewers were spawned survive their own evidence?

    Four failures, all silent without this:

      1. A role never declared what it held. Then "11 of 11 run (named agents)" is a claim about
         eleven tool grants backed by nothing, and a review whose citation validator could not
         reach a DOI is indistinguishable from one whose could.
      2. A role declared MISMATCH and the header still says named agents. That is the report
         claiming a capability its own reviewer said it did not have -- which is worse than the
         missing grant, because it is the part a reader would rely on.
      3. A role declared `ok` and named tools that are not the ones the process file grants it --
         including naming none at all. Until this check existed a report of eleven rows reading
         `GRANT n ok — nothing whatsoever` exited 0, because the match read the verdict token and
         never the list beside it. The gate could not fail in the direction it was built to fail
         in, and two public documents said it could.
      4. A role declared BOTH verdicts. The old loop kept the last match, so a real MISMATCH
         became `ok` as soon as anything later in the file said so -- and every compiled agent
         file contains the literal string `GRANT n ok — <its tools>`, which means the report that
         quotes its own agent files, the most thorough report anyone would write, is the one that
         laundered its reviewers' verdicts. No adversary required.

    A MISMATCH is NOT itself a failure. A fallback run is a legitimate run; it just may not be
    described as something else. Making the mismatch fatal would only teach people to stop
    declaring it. A CONTRADICTION is a failure, and deliberately not resolved in either
    direction: last-wins is how (4) happened, and any-mismatch-wins fails the honest quotation in
    (4)'s second half. A report that says both cannot be read mechanically, and saying so is the
    only answer that does not silently pick a verdict on the author's behalf.
    """
    path = pathlib.Path(report_path)
    if not path.is_file():
        print("murderboard_agents: cannot read report %s" % path, file=sys.stderr)
        return 2
    text = path.read_text(encoding="utf-8")

    # EVERY declaration is kept, not the last one. What is done with a role that made more than
    # one is decided below, where it can be reported instead of resolved.
    declared = {}
    for m in GRANT_LINE_RE.finditer(text):
        raw = (m.group(3) or "").strip().rstrip("|").strip()
        if PLACEHOLDER_RE.search(raw):
            continue
        declared.setdefault(int(m.group(1)), []).append((m.group(2).lower(), raw))

    problems = []
    verdicts = {}
    for num in sorted(grants):
        rows = declared.get(num)
        if not rows:
            problems.append(
                "role %d never declared its grant — no `GRANT %d ok` or `GRANT %d MISMATCH` "
                "line in the report" % (num, num, num))
            continue

        seen = {v for v, _ in rows}
        if len(seen) > 1:
            problems.append(
                "role %d declared BOTH `ok` and `MISMATCH` — the report cannot be read "
                "mechanically, and this tool will not pick one. If a quoted agent file supplied "
                "the second, break the quotation; otherwise state the verdict the reviewer "
                "actually reached, once" % num)
            continue

        verdict = seen.pop()
        verdicts[num] = verdict
        if verdict != "ok":
            # `missing X; holds Y` is prose, not a tool list, and comparing it against the table
            # would only punish the reviewer who told the truth.
            continue

        lists = {tool_set(raw) for _, raw in rows}
        if len(lists) > 1:
            problems.append(
                "role %d declared `ok` more than once with different tool lists (%s) — the "
                "report cannot be read mechanically"
                % (num, "; ".join(sorted(", ".join(sorted(l)) or "nothing" for l in lists))))
            continue

        held = lists.pop()
        granted = tool_set(grants[num]["tools"])
        if not held:
            problems.append(
                "role %d declared `ok` but named no tools — `ok` is a claim that the reviewer "
                "held exactly `%s`, so it has to say so" % (num, grants[num]["tools"]))
        elif held != granted:
            problems.append(
                "role %d declared `ok` while naming %s — the process file grants it %s. Either "
                "the declaration is wrong, or the run was a MISMATCH and should say so"
                % (num, ", ".join(sorted(held)), grants[num]["tools"]))

    header = ROLES_LINE_RE.search(text)
    mode = header.group(3).strip().lower() if header else None
    if header is None:
        problems.append(
            "the run record has no `roles: <n> of <n> run (<how>)` line, so it does not say "
            "how its reviewers were spawned")
    else:
        mismatched = sorted(n for n, v in verdicts.items() if v == "mismatch")
        if mismatched and any(k in mode for k in NAMED_MODES):
            problems.append(
                "the header claims %r while role%s %s reported MISMATCH — say the run took a "
                "fallback path, or re-run it with the grants in place"
                % (header.group(3).strip(), "" if len(mismatched) == 1 else "s",
                   ", ".join(str(n) for n in mismatched)))

    if problems:
        for p in problems:
            print("  %s" % p, file=sys.stderr)
        print("murderboard_agents: %s does not account for the grants its reviewers held"
              % path, file=sys.stderr)
        return 1

    mism = sum(1 for v in verdicts.values() if v == "mismatch")
    print("murderboard_agents: all %d roles declared a grant in %s (%d ok, %d mismatch), the "
          "tools each `ok` named are the ones the process file grants it, and the header agrees"
          % (len(grants), path, len(verdicts) - mism, mism))
    return 0


def cmd_list(agents, target):
    for name, body in sorted(agents.items()):
        num = int(name.split("-", 1)[0])
        agent_name = re.search(r"^name: (.+)$", body, re.M).group(1)
        print("%d\t%s\t%s" % (num, agent_name, target / name))
    return 0


# --- selftest -----------------------------------------------------------------

MINI = """# process
## The process
1. **Draft** the document.
## The review team

Spawn these as parallel subagents, each given the draft.

**Each role returns a structured finding list**, one row per finding.

Harness-facing trivia that must not reach an agent file.

**Roles are split by what it COSTS to satisfy them.** Boundary prose.

1. **Claim & data verifier — "Prove It."** Extract every claim. Second sentence here.
   - a sub-bullet
2. **Line editor — "Kill Your Darlings."** Clarity and precision.

### What each role must be able to reach

**No reviewer may edit the artifact.** Findings go to the main thread.

**Every reviewer declares its grant before it reviews.** First output line, `GRANT <n> ok` or
`GRANT <n> MISMATCH`.

| # | role | may reach | model |
|---|---|---|---|
| 1 | Prove It | Read, Bash | inherit |
| 2 | Kill Your Darlings | Read | inherit |

### The team is not optional

A role with genuinely nothing to check returns **"no findings, and here is what I checked"**.

## Literature handling
1. **Check the library FIRST.** blah
"""


def cmd_selftest():
    passed = failed = 0

    def ok(name, cond, detail=""):
        nonlocal passed, failed
        if cond:
            passed += 1
            print("  ok   %s" % name)
        else:
            failed += 1
            print("  FAIL %s %s" % (name, detail))

    def raises(name, text):
        nonlocal passed, failed
        with tempfile.TemporaryDirectory() as d:
            p = pathlib.Path(d) / "p.md"
            p.write_text(text, encoding="utf-8")
            try:
                compile_agents(p)
            except ProcessError:
                passed += 1
                print("  ok   %s" % name)
                return
        failed += 1
        print("  FAIL %s (expected ProcessError, got none)" % name)

    with tempfile.TemporaryDirectory() as d:
        d = pathlib.Path(d)
        p = d / "p.md"
        p.write_text(MINI, encoding="utf-8")
        agents = compile_agents(p)

        ok("parses 2 roles, ignores the decoy numbered lists", len(agents) == 2, str(sorted(agents)))
        ok("filenames are NN-slug.md", sorted(agents) == ["01-prove-it.md", "02-kill-your-darlings.md"],
           str(sorted(agents)))
        body = agents["01-prove-it.md"]
        ok("grant reaches the frontmatter", "tools: Read, Bash" in body)
        ok("description is QUOTED (role prose contains ': ', which breaks a bare YAML scalar)",
           all(b.splitlines()[2].startswith('description: "') and b.splitlines()[2].endswith('"')
               for b in agents.values()))
        ok("role 2's narrower grant is not role 1's", "tools: Read\n" in agents["02-kill-your-darlings.md"])
        ok("no reviewer gets Edit or Write", not any("Edit" in b.split("---")[1] or "Write" in b.split("---")[1]
                                                     for b in agents.values()))
        ok("checklist body is carried through", "Extract every claim" in body)
        ok("sub-bullets are dedented", "\n- a sub-bullet" in body)
        ok("shared no-edit rule is carried", "No reviewer may edit the artifact" in body)
        ok("silence-is-not-a-result is carried", "no findings, and here is what I checked" in body)
        ok("boundary prose is carried", "Roles are split by what it COSTS" in body)
        # The instruction to SPAWN reviewers is addressed to the harness. Compiled into an
        # agent file it would tell a reviewer to spawn the team it is already a member of.
        ok("the spawn instruction never reaches an agent file",
           all("Spawn these as parallel subagents" not in b for b in agents.values()))
        ok("the finding-list contract DOES reach every agent file",
           all("structured finding list" in b for b in agents.values()))
        ok("harness-facing preamble above the split line is dropped",
           all("Harness-facing trivia" not in b for b in agents.values()))
        ok("another role's checklist is absent", "Clarity and precision" not in body)

        target = d / "agents"
        ok("check fails before write", cmd_check(agents, target) == 1)
        cmd_write(agents, target)
        ok("check passes after write", cmd_check(agents, target) == 0)
        (target / "01-prove-it.md").write_text("hand edited\n", encoding="utf-8")
        ok("a hand-edited agent file FAILS check", cmd_check(agents, target) == 1)
        cmd_write(agents, target)
        # NEGATIVE CONTROL, and it used to be the positive one. This file is named like ours
        # and carries no banner, so it is somebody else's. Both assertions below were the
        # opposite before the destructive-delete fix, and both had to flip: the old pair is
        # exactly what a consumer's own agent looked like on the way to being unlinked.
        (target / "99-ghost.md").write_text("stale role\n", encoding="utf-8")
        ok("a BANNERLESS orphan does not fail check", cmd_check(agents, target) == 0)
        cmd_write(agents, target)
        ok("write does not remove a bannerless orphan", (target / "99-ghost.md").exists())
        (target / "99-ghost.md").unlink()

        # --- the destructive-delete incident -----------------------------------------
        # Every consumer-facing instruction points --dir at .claude/agents, which is the
        # SHARED project agent directory. These five cases are the whole reason `ours()`
        # exists; each one was a file that got deleted before it did.
        mine = target / "my-own-agent.md"
        mine.write_text("---\nname: my-own-agent\n---\nsomebody else's reviewer\n", encoding="utf-8")
        lookalike = target / "04-not-mine.md"          # matches OUR naming, not our banner
        lookalike.write_text("---\nname: theirs\n---\nnamed like ours, not ours\n", encoding="utf-8")
        binary = target / "07-binary.md"
        binary.write_bytes(b"\xff\xfe\x00\x01not utf-8")

        ok("a foreign agent file does NOT make check fail", cmd_check(agents, target) == 0)
        cmd_write(agents, target)
        ok("write leaves a foreign agent file alone", mine.is_file())
        ok("write leaves a file NAMED like ours but lacking the banner", lookalike.is_file())
        ok("write leaves an unreadable file alone", binary.is_file())
        ok("the eleven are still correct alongside foreign files", cmd_check(agents, target) == 0)

        # ...and ours is still swept, so a renamed role cannot linger under an old name.
        ghost = target / "98-ghost.md"
        ghost.write_text(agents["01-prove-it.md"], encoding="utf-8")   # carries the banner
        ok("a banner-carrying orphan still FAILS check", cmd_check(agents, target) == 1)
        cmd_write(agents, target)
        ok("write still removes a banner-carrying orphan", not ghost.exists())
        ok("...without taking the foreign files with it", mine.is_file() and binary.is_file())
        mine.unlink(); lookalike.unlink(); binary.unlink()

        ok("--dir pointing at a FILE is exit 2, not a traceback",
           cmd_write(agents, d / "p.md") == 2 and cmd_check(agents, d / "p.md") == 2)

        # --- the namespace, which is what makes the sweep safe by construction --------
        consumer = d / "consumer"
        (consumer / ".claude" / "agents").mkdir(parents=True)
        (consumer / ".claude" / "agents" / "their-agent.md").write_text("theirs\n", encoding="utf-8")
        ok("a consumer's default is BENEATH the shared dir, not in it",
           default_dir(consumer) == consumer / ".claude" / "agents" / "murderboard")
        cmd_write(agents, default_dir(consumer))
        ok("...so writing cannot even see the consumer's own agent",
           (consumer / ".claude" / "agents" / "their-agent.md").is_file())

        # The murderboard's own checkout is the exception: it IS the plugin, and a plugin
        # ships agents at its root. Detected by NAME, because any consumer may publish a
        # plugin and "has a .claude-plugin/" would send their reviewers somewhere unread.
        src = d / "src"
        (src / ".claude-plugin").mkdir(parents=True)
        (src / "agents").mkdir()
        (src / ".claude-plugin" / "plugin.json").write_text('{"name": "murderboard"}', encoding="utf-8")
        ok("the murderboard's own checkout keeps agents/ at its root",
           default_dir(src) == src / "agents")
        (src / ".claude-plugin" / "plugin.json").write_text('{"name": "someone-else"}', encoding="utf-8")
        ok("ANOTHER project's plugin does not get the exception",
           default_dir(src) == src / ".claude" / "agents" / "murderboard")
        (src / ".claude-plugin" / "plugin.json").write_text("not json", encoding="utf-8")
        ok("an unreadable manifest falls back to the namespace, not a traceback",
           default_dir(src) == src / ".claude" / "agents" / "murderboard")

        # --- verify: does the report account for the grants its reviewers held? -------
        grants = compile_all(p)["grants"]

        def report(name, body):
            r = d / name
            r.write_text(body, encoding="utf-8")
            return cmd_verify(str(r), grants)

        clean = ("- roles: 2 of 2 run (named agents)\n"
                 "| 1 | Prove It | GRANT 1 ok — Read, Bash |\n"
                 "| 2 | Kill Your Darlings | GRANT 2 ok — Read |\n")
        ok("a report where every role declared its grant passes", report("clean.md", clean) == 0)

        ok("a role that never declared its grant FAILS",
           report("silent.md", clean.replace("| 2 | Kill Your Darlings | GRANT 2 ok — Read |\n",
                                             "| 2 | Kill Your Darlings | no findings |\n")) == 1)

        # The whole point of the gate: the header may not claim a capability the reviewer denied.
        ok("MISMATCH under a 'named agents' header FAILS",
           report("lying.md", clean.replace("GRANT 2 ok — Read",
                                            "GRANT 2 MISMATCH — holds Write")) == 1)
        ok("the same MISMATCH under a 'fallback' header PASSES",
           report("honest.md",
                  clean.replace("GRANT 2 ok — Read", "GRANT 2 MISMATCH — holds Write")
                       .replace("(named agents)", "(inline fallback)")) == 0)

        ok("a report with no `roles:` mode line FAILS",
           report("nomode.md", clean.replace("- roles: 2 of 2 run (named agents)\n", "")) == 1)
        ok("an unreadable report is exit 2", cmd_verify(str(d / "nope.md"), grants) == 2)

        # --- the tool list after the dash is READ. Every assertion below returned 0 from the
        # --- day this tool was written until the day these were added.
        ok("`ok` naming no tools at all FAILS — the shape that used to pass eleven times over",
           report("empty.md", clean.replace("GRANT 1 ok — Read, Bash",
                                            "GRANT 1 ok — nothing whatsoever")) == 1)
        ok("`ok` with the dash and nothing after it FAILS",
           report("bare.md", clean.replace("GRANT 1 ok — Read, Bash", "GRANT 1 ok")) == 1)
        ok("`ok` naming FEWER tools than the process file grants FAILS",
           report("short.md", clean.replace("GRANT 1 ok — Read, Bash", "GRANT 1 ok — Read")) == 1)
        ok("`ok` naming a tool the process file does NOT grant FAILS",
           report("extra.md", clean.replace("GRANT 1 ok — Read, Bash",
                                            "GRANT 1 ok — Read, Bash, Write")) == 1)
        # Generous about format, strict about substance: a reviewer typing its own tools back is
        # not required to reproduce the table's order or capitalisation.
        ok("the same tools in another order and case PASS",
           report("order.md", clean.replace("GRANT 1 ok — Read, Bash",
                                            "GRANT 1 ok — bash,  READ")) == 0)

        # --- last-match-wins: the laundering, and the honest report it must not punish --------
        mismatch2 = clean.replace("GRANT 2 ok — Read", "GRANT 2 MISMATCH — missing Read")
        ok("a MISMATCH that a LATER `ok` would have overwritten FAILS as a contradiction",
           report("laundered.md",
                  mismatch2 + "\nAppendix, the agent file role 2 was spawned from:\n\n"
                              "    GRANT 2 ok — Read\n") == 1)
        # The bait is instruction text, not a verdict. A run record that quotes its own agent
        # files -- the most thorough one anyone would write -- must not read as a mismatch.
        ok("quoting the agent file's MISMATCH TEMPLATE does not fabricate a mismatch",
           report("quoted.md",
                  clean + "\nThe form each agent is told to use:\n\n"
                          "    GRANT 2 MISMATCH — missing <tools>; holds <forbidden tools>\n") == 0)
        ok("a declaration made only of placeholders declares nothing, so the role is UNDECLARED",
           report("placeholder.md", clean.replace("GRANT 2 ok — Read",
                                                  "GRANT 2 ok — <tools>")) == 1)
        ok("`ok` twice with different tool lists FAILS rather than picking one",
           report("twice.md", clean + "\n| 1 | Prove It | GRANT 1 ok — Read |\n") == 1)

    raises("a process file with no team section is an ERROR", "# nothing\n")
    raises("a team section with no roles is an ERROR",
           "## The review team\n\nprose only\n\n## Next\n")
    raises("a missing grants table is an ERROR", MINI.replace(GRANTS_HEADING, "### Something else"))
    raises("a role with no grant row is an ERROR", MINI.replace("| 2 | Kill Your Darlings | Read | inherit |\n", ""))
    raises("a grant row with no role is an ERROR",
           MINI.replace("| 2 | Kill Your Darlings | Read | inherit |",
                        "| 2 | Kill Your Darlings | Read | inherit |\n| 7 | Ghost | Read | inherit |"))
    raises("a reworded shared block is an ERROR, not a silent drop",
           MINI.replace("A role with genuinely nothing to check returns", "A role with nothing to check returns"))

    print("\n%d passed, %d failed" % (passed, failed))
    return 0 if failed == 0 else 1


# --- args ---------------------------------------------------------------------


def main(argv):
    ap = argparse.ArgumentParser(add_help=True, description=__doc__.splitlines()[0])
    ap.add_argument("command", nargs="?", choices=("write", "check", "list", "verify"))
    ap.add_argument("report", nargs="?", help="the run record, for `verify`")
    ap.add_argument("--process", help="path to doc_review_process.md")
    ap.add_argument("--dir", help="where the agent files live (default: <repo root>/agents)")
    ap.add_argument("--selftest", action="store_true")
    # So a harness can ASK where the agent files go instead of reimplementing the rule.
    # The skill used to carry its own copy of it and got it wrong: it tested "is this repo a
    # plugin", which is true of any consumer that publishes one, and would have sent their
    # reviewers to a top-level `agents/` the harness never reads.
    ap.add_argument("--print-dir", action="store_true",
                    help="print the default agent directory for this repo and exit")
    args = ap.parse_args(argv)

    if args.print_dir:
        print(default_dir(repo_root()))
        return 0
    if args.selftest:
        return cmd_selftest()
    if not args.command:
        ap.error("one of write / check / list / verify is required (or --selftest)")
    if args.command == "verify" and not args.report:
        ap.error("usage: murderboard_agents.py verify REPORT.md")

    try:
        process = resolve_process(args.process)
        compiled = compile_all(process)
    except ProcessError as e:
        print("murderboard_agents: %s" % e, file=sys.stderr)
        return 2

    if args.command == "verify":
        return cmd_verify(args.report, compiled["grants"])

    target = pathlib.Path(args.dir) if args.dir else default_dir(repo_root())
    return {"write": cmd_write, "check": cmd_check, "list": cmd_list}[args.command](
        compiled["files"], target)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
