#!/usr/bin/env python3
"""`agents/` must be the compiled output of doc_review_process.md, and nothing else.

THE FAILURE THIS PREVENTS. Eleven agent files that a person can edit are eleven second
copies of eleven rules. This repo has already paid once for two copies of one document
drifting apart, and the review team is a worse place for it to happen: an edited agent file
changes what a reviewer actually checks while `doc_review_process.md` -- the thing consumers
read, vendor and cite -- still says the old thing. Nothing in the report would show it. The
roster would still count eleven.

So: regenerate from the process file and diff. A hand-edit fails here, and the fix is always
to move the change into the process file and re-run `murderboard_agents.py write`.

The other checks are on the compiled result rather than the compiler, because
`murderboard_agents.py --selftest` proves the compiler works on a fixture and this proves it
worked on the real file:

  - one agent per role the ROSTER finds, so the two derivations of "who is on the team"
    cannot disagree (the roster gates the finished report; these gate what gets spawned);
  - frontmatter that actually parses, without pyyaml on the runner;
  - no reviewer holding Edit / Write / NotebookEdit.

Offline: reads files in this repo and runs one local script.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FAILURES = []

FORBIDDEN_TOOLS = ("Edit", "Write", "NotebookEdit", "MultiEdit")


def check(label, ok, detail=""):
    print(("  PASS  " if ok else "  FAIL  ") + label + (("   " + detail) if detail else ""))
    if not ok:
        FAILURES.append(label)


def frontmatter(text):
    """Minimal `key: value` frontmatter parse — no pyyaml on the CI runner.

    Deliberately strict about the one thing that bites: a value containing ': ' must be
    quoted, or a real YAML parser reads it as a nested mapping and the agent fails to load.
    Role descriptions are sliced from prose full of colons, so this is not theoretical.
    """
    if not text.startswith("---\n"):
        return None, "no opening --- fence"
    body = text[4:]
    end = body.find("\n---\n")
    if end < 0:
        return None, "no closing --- fence"
    out = {}
    for line in body[:end].splitlines():
        m = re.match(r"^([A-Za-z_]+): (.*)$", line)
        if not m:
            return None, "unparseable frontmatter line: %r" % line
        key, value = m.group(1), m.group(2).strip()
        if value.startswith('"') and value.endswith('"') and len(value) > 1:
            value = value[1:-1]
        elif ": " in value:
            return None, "value for %r contains ': ' but is not quoted" % key
        out[key] = value
    return out, ""


def main():
    print("agents/ is generated, and agrees with the process file")

    rc = subprocess.run(
        [sys.executable, str(ROOT / "murderboard_agents.py"), "check"],
        cwd=ROOT, capture_output=True, text=True,
    )
    check("murderboard_agents.py check passes (agents/ == compiled process file)",
          rc.returncode == 0, rc.stderr.strip() or rc.stdout.strip())

    roster = subprocess.run(
        ["bash", str(ROOT / "murderboard_roster.sh"), "list"],
        cwd=ROOT, capture_output=True, text=True,
    )
    roster_nums = [ln.split("\t")[0] for ln in roster.stdout.splitlines() if ln.strip()]

    files = sorted((ROOT / "agents").glob("*.md"))
    check("agents/ is not empty", bool(files), "%d files" % len(files))
    check("one agent file per role the roster finds",
          len(files) == len(roster_nums),
          "%d agent files vs %d roster rows" % (len(files), len(roster_nums)))

    file_nums = [f.name.split("-", 1)[0].lstrip("0") or "0" for f in files]
    check("agent filenames carry the roster's role numbers",
          file_nums == roster_nums, "%s vs %s" % (file_nums, roster_nums))

    names = set()
    for path in files:
        text = path.read_text(encoding="utf-8")
        fm, why = frontmatter(text)
        rel = "agents/" + path.name
        if fm is None:
            check("%s frontmatter parses" % rel, False, why)
            continue
        check("%s frontmatter parses" % rel, True)
        for key in ("name", "description", "tools", "model"):
            check("%s has %s" % (rel, key), key in fm and bool(fm[key]))
        tools = [t.strip() for t in fm.get("tools", "").split(",") if t.strip()]
        bad = [t for t in tools if t in FORBIDDEN_TOOLS]
        check("%s cannot edit the artifact it reviews" % rel, not bad, ",".join(bad))
        check("%s is granted something to read with" % rel, "Read" in tools)
        check("%s carries the generated banner" % rel, "GENERATED by murderboard_agents.py" in text)
        check("%s name is unique" % rel, fm.get("name") not in names, fm.get("name", ""))
        names.add(fm.get("name"))

    # The two roles the process file forbids from reasoning from memory are the two whose
    # sources are outside the repo. A grant table that quietly drops their web access turns
    # them into roles that report on citations and methods they never opened.
    for stem, tool in (("02-doi-or-die", "WebSearch"), ("06-rtfm", "WebSearch")):
        path = ROOT / "agents" / (stem + ".md")
        fm, _ = frontmatter(path.read_text(encoding="utf-8")) if path.is_file() else (None, "")
        check("agents/%s.md can reach %s" % (stem, tool),
              bool(fm) and tool in fm.get("tools", ""))

    print()
    if FAILURES:
        print("FAILED: %d" % len(FAILURES))
        for f in FAILURES:
            print("  - " + f)
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
